packages: []
allowBuilds:
  esbuild: true
  workerd: true
  "@tailwindcss/oxide": true
  sharp: true
minimumReleaseAge: 1440
patchedDependencies:
  "@cosmos.gl/graph@3.4.1": patches/@cosmos.gl__graph@3.4.1.patch
