// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Bur = { id: number, date: string, title: string, ops: Array<[string, string, string]>, };

export type CommunitiesOut = { regions: Array<NamedCommunity>, continents: Array<NamedCommunity>, continent_of_region: Array<number>, };

export type Event = { date: string, kind: string, other: string, source: string, approx?: boolean, };

export type Feature = { community: number, label: boolean, anchor: [number, number], cells: number, hexes: Array<number>, };

export type LevelOut = { hex_size: number, origin: [number, number], features: Array<Feature>, };

export type Manifest = { export_date: string, generated_at: string, node_floor: number, playground_floor: number, nodes: number, edges: number, space_size: number, weight_max: number, max_degree: number, base_links: number, tail_neighbors: number, text_shards: Array<number>, tile_cutoffs: Array<number>, adj_shard_size: number, years: Array<number>, years_over: number, files: Record<string, number>, parts: { [key in string]: number }, };

export type NamedCommunity = { name: string, tags: Array<string>, size: number, };

export type NodeImplication = [number, number, number | null, boolean];

export type NodeText = { wiki?: string | null, links?: Array<number>, aliases?: Array<string>, children?: Array<string>, parents?: Array<string>, history?: Array<Event>, ratings: [number, number, number], region: number, edges?: Array<number>, similar?: Array<number>, };

export type TerritoriesOut = { regions: LevelOut, continents: LevelOut, };
